### ISSUE TITLE
Hata

### ISSUE THREAD

**Issue by GrowtopiaNoobs2** [maxmanusv1/Maxidatter---Growtopia-Savedat-Stealer#2]
Kodlarda hata var sanırım kardeşim 4 yer var authsecret onu girdim basepath vardı onuda website adını girdim  sonra ip,countty pc namr falan filanin geldigini gördüm   sonra savedats,chromepass kısmı için storage websitesi adını girdim fakat save.dats googlepass gelmedi detaylı olarak anlatabilirmisin acaba ne yapacagımı anlatırsan minnetar kalırım 🙏

**Comment by GrowtopiaNoobs2** [comment]
Bu arada proje saglam helal olsun kardesim bir türkün bunları yapabildigini görmek duygulandırdı açıkcası ulasabilecegim discord adreside birakirsan sevinirm

**Comment by maxmanusv1** [comment]
> Kodlarda hata var sanırım kardeşim 4 yer var authsecret onu girdim basepath vardı onuda website adını girdim sonra ip,countty pc namr falan filanin geldigini gördüm sonra savedats,chromepass kısmı için storage websitesi adını girdim fakat save.dats googlepass gelmedi detaylı olarak anlatabilirmisin acaba ne yapacagımı anlatırsan minnetar kalırım 🙏

Bazı yerlerde Firebase storage yolunu göstermen lazımdı eğer gösterdiğin halde save.datı göndermediyse değiştirdiğin yerleri tekrar kontrol etmeni öneririm. Kodlar Github'a yüklenmeden önce denenmişti yani bu kısımda bir hata olabileceğini sanmıyorum.

**Comment by maxmanusv1** [comment]
> Bu arada proje saglam helal olsun kardesim bir türkün bunları yapabildigini görmek duygulandırdı açıkcası ulasabilecegim discord adreside birakirsan sevinirm

Teşekkür ederim, Discord hesabımı eskiden Github hesabımda gösteriyordum fakat artık göstermeme kararı aldım.

**Comment by GrowtopiaNoobs2** [comment]
> > Bu arada proje saglam helal olsun kardesim bir türkün bunları yapabildigini görmek duygulandırdı açıkcası ulasabilecegim discord adreside birakirsan sevinirm
> 
> Teşekkür ederim, Discord hesabımı eskiden Github hesabımda gösteriyordum fakat artık göstermeme kararı aldım.

Kodlar çalışmıyor ona ne diceksin tutorial çekebilme imkanjn varmı kardesim thtde gördüm

**Comment by maxmanusv1** [comment]
> > > Bu arada proje saglam helal olsun kardesim bir türkün bunları yapabildigini görmek duygulandırdı açıkcası ulasabilecegim discord adreside birakirsan sevinirm
> > 
> > 
> > Teşekkür ederim, Discord hesabımı eskiden Github hesabımda gösteriyordum fakat artık göstermeme kararı aldım.
> 
> Kodlar çalışmıyor ona ne diceksin tutorial çekebilme imkanjn varmı kardesim thtde gördüm

Kodların çalışmama imkanı yok, deneyipte yükledim sonuçta buraya. Tutorial yerine direk Builder'ini yapasım var. Discorddan çok fazla mesaj gelmişti o yüzden Discord'u vermeme kararı aldım.

**Comment by GrowtopiaNoobs2** [comment]
> > > > Bu arada proje saglam helal olsun kardesim bir türkün bunları yapabildigini görmek duygulandırdı açıkcası ulasabilecegim discord adreside birakirsan sevinirm
> > > 
> > > 
> > > Teşekkür ederim, Discord hesabımı eskiden Github hesabımda gösteriyordum fakat artık göstermeme kararı aldım.
> > 
> > 
> > Kodlar çalışmıyor ona ne diceksin tutorial çekebilme imkanjn varmı kardesim thtde gördüm
> 
> Kodların çalışmama imkanı yok, deneyipte yükledim sonuçta buraya. Tutorial yerine direk Builder'ini yapasım var. Discorddan çok fazla mesaj gelmişti o yüzden Discord'u vermeme kararı aldım.

Kardesim Bexpg#5634 Eklersen sevinirim Çok rahatsız etmem zaten storageyle ilgili 1soru soracam builder konusundada yardımcı olabilirim elime 2-3 saglam source var c#

**Comment by b0tahmet** [comment]
@GrowtopiaNoobs2 kodlar gayet güzel çalışıyor bizzat denedim bunu söylemek için hesap açtım amına koyayım.

**Comment by GrowtopiaNoobs2** [comment]
> @GrowtopiaNoobs2 kodlar gayet güzel çalışıyor bizzat denedim bunu söylemek için hesap açtım amına koyayım.

Discordtan yazarmısın krdsm storageye save.dat gelmiyor

**Comment by GrowtopiaNoobs2** [comment]
Calismiyor amk

**Comment by maxmanusv1** [comment]
> Calismiyor amk

2 Tane link ve anahtarı kopyalamayı beceremeyecek kadar kötüysen bu benim sorunum olmamalı bence. Kodlar buraya konulmadan önce denenmiş vaziyette koyuldu. Save.dat çekmek yerine Decode edip çekersin... NuGet paketini güncellemeyi dene, Firebase kurallarının hepsini izin vermeyi unutma. Buradan tüm söyleyebileceklerim bu kadar.
